#!/bin/bash

# EDIT This Section for The Certificate Information
CO="US"                         # 2 LETTER COUNTRY
ST="TX"                         # 2 LETTER STATE
LO="TX"                         # 2 LETTER LOCATION
OR="TEMPLATE"                   # ORGANIZATION
OU="Certification Authority"    # OU (Certificate Authority)
CN="template.example.com"       # COMMON NAME (www.example.com)

# Check if Certificates Exist
if [ "$(ls -A ./cert)" ]; then

    printf "[!] Certificates Already Created!\n"

    # Check if User wants to Delete Certificates
    printf "[?] Do you want to delete existing certificates to create new ones? (Y)es/(N)o: "
    read answer

    # Convert Variable "answer" to Uppercase
    answer=$(echo "$answer" | tr '[:lower:]' '[:upper:]')

    case $answer in
        "Y"|"YES")
            # Deleting Previous Certificates
            printf "[+] Deleting Certificates...\n"
            rm -f ./cert/{fullchain.pem,privkey.pem}

            # Creating New Certificates
            openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
                -keyout ./cert/privkey.pem \
                -out ./cert/fullchain.pem \
                -subj "/C=$CO/ST=$ST/L=$LO/O=$OR/OU=$OU/CN=$CN"
            
            printf "[i] Done\n"
            ;;

        "N"|"NO")
            printf "[+] Not Deleting Certificates.\n[i] Done\n"
            ;;

        *)
            # Exit/Fail When Non-Valid Input is Recieved
            printf "[!] Invalid Input. Please enter either (Y)es/(N)o\n"
            exit 1
            ;;
    esac
else
    # Creating New Certificates
    openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
        -keyout ./cert/privkey.pem \
        -out ./cert/fullchain.pem \
        -subj "/C=$CO/ST=$ST/L=$LO/O=$OR/OU=$OU/CN=$CN"
fi

# Exit Script
exit 0